# .github/workflows/worker.yml
name: 🛠️ Worker

on:
  schedule:
    # кожні 2 години (в UTC)
    - cron:  '0 */2 * * *'
  workflow_dispatch:  # дозволяє запуск вручну з UI

jobs:
  build_and_run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Load environment variables
      run: echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" >> $GITHUB_ENV
    - run: echo "CHAT_ID=${{ secrets.CHAT_ID }}" >> $GITHUB_ENV

    - name: Initialize database
      run: python init_db.py

    - name: Run worker
      run: python worker.py
